version: '3'
services:

  issuer-server:
    container_name: issuer-server
    build:
      context: .
      dockerfile: ./Dockerfile_server.run
    ports:
      - 5229:5229
    command: >
      node MSP_server.js
        --ip ${ip_address}
        --port 5229
        --name Creditcard
        --agentUrl http://${ip_address}:5080
        --schemaName CreditCard
        --imageUrl https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Mastercard_2019_logo.svg/1200px-Mastercard_2019_logo.svg.png
    depends_on:
      - issuer-agent

  issuer-tails-server:
      container_name: issuer-tails-server
      build:
        context: ./indy-tails-server
        dockerfile: ./docker/Dockerfile.tails-server
      ports:
        - 6545:6545
      command: >
        tails-server
          --host 0.0.0.0
          --port 6545
          --log-level debug
          --storage-path /home/indy/tails
      # volumes:
      #  - ${dir_name}/.indy_tails:/home/indy/tails

  issuer-agent:
      container_name: issuer-agent
      build:
        context: ./aries-cloudagent-python
        dockerfile: ./docker/Dockerfile.run
      ports:
        - 5000:5000
        - 5080:5080
      entrypoint: aca-py
      command: >
        start
          --auto-provision
          --tails-server-base-url http://${ip_address}:6545
          --webhook-url http://${ip_address}:5229
          --auto-respond-credential-proposal
          --auto-respond-credential-offer
          --auto-respond-credential-request
          --auto-verify-presentation
          --inbound-transport http 0.0.0.0 5000
          --inbound-transport ws 0.0.0.0 5001
          --outbound-transport ws
          --outbound-transport http
          --genesis-url http://${ip_address}:9000/genesis
          --log-level info
          --seed 000000000000000000000000Steward3
          --wallet-type indy
          --wallet-key StewardWallet3
          --wallet-name StewardWallet3
          --admin-insecure-mode
          --admin 0.0.0.0 5080
          -e http://${ip_address}:5000
          -l MasterCard
      depends_on:
        - issuer-tails-server

  routing-webapp:
    container_name: routing-webapp
    build:
      context: .
      dockerfile: ./Dockerfile_webapp.run
    ports:
      - 3000:3000
    # command: >
      #tail -f /dev/null
      # npm start

  msp1-server:
    container_name: msp1-server
    build:
      context: .
      dockerfile: ./Dockerfile_server.run
    ports:
      - 8000:8000
    command: >
      node MSP_server.js
        --ip ${ip_address}
        --port 8000
        --name Bahn
        --agentUrl http://${ip_address}:7080
        --schemaName Bahn-Ticket
        --imageUrl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Deutsche_Bahn_AG-Logo.svg/250px-Deutsche_Bahn_AG-Logo.svg.png
    depends_on:
      - msp1-agent
    volumes:
      - ${dir_name}/config.json:/usr/src/app/config.json
  
  msp1-tails-server:
    container_name: msp1-tails-server
    build:
      context: ./indy-tails-server
      dockerfile: ./docker/Dockerfile.tails-server 
    ports:
      - 6543:6543
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --log-level debug
        --storage-path /home/indy/tails
    # volumes:
    #  - ${dir_name}/.indy_tails:/home/indy/tails


  msp1-agent:
    container_name: msp1-agent
    build:
      context: ./aries-cloudagent-python
      dockerfile: ./docker/Dockerfile.run
    ports:
      - 7000:7000
      - 7080:7080
    # healthcheck:
      # test: [ "CMD", "curl", "-f", "http://${ip_address}:7080" ]
      # interval: 4s
      # timeout: 4s
      # retries: 10
      # start_period: 5s
    entrypoint: aca-py
    command: >
      start
        --auto-provision
        --tails-server-base-url http://${ip_address}:6543 
        --webhook-url http://${ip_address}:8000
        --auto-respond-credential-proposal 
        --auto-respond-credential-offer 
        --auto-respond-credential-request
        --auto-verify-presentation 
        --inbound-transport http 0.0.0.0 7000 
        --inbound-transport ws 0.0.0.0 7001 
        --outbound-transport ws 
        --outbound-transport http
        --genesis-url http://${ip_address}:9000/genesis
        --log-level info
        --seed 000000000000000000000000Steward1
        --wallet-type indy 
        --wallet-key StewardWallet1
        --wallet-name StewardWallet1
        --admin-insecure-mode 
        --admin 0.0.0.0 7080 
        -e http://${ip_address}:7000
        -l DeutscheBahn
    depends_on:
      - msp1-tails-server
    # volumes:
      # - ${dir_name}/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis
      # - ${dir_name}/.indy_client_hr:/home/indy/.indy_client

  msp2-server:
    container_name: msp2-server
    build:
      context: .
      dockerfile: ./Dockerfile_server.run
    ports:
      - 9229:9229
    command: >
      node MSP_server.js
        --ip ${ip_address}
        --port 9229
        --name Flight
        --agentUrl http://${ip_address}:8050
        --schemaName Lufthansa-Ticket
        --imageUrl https://cdn.iconscout.com/icon/free/png-256/lufthansa-282468.png
    depends_on:
      - msp2-agent

  msp2-tails-server:
    container_name: msp2-tails-server
    build:
      context: ./indy-tails-server
      dockerfile: ./docker/Dockerfile.tails-server
    ports:
      - 6544:6544
    command: >
      tails-server
        --host 0.0.0.0
        --port 6544
        --log-level debug
        --storage-path /home/indy/tails
    # volumes:
    #  - ${dir_name}/.indy_tails:/home/indy/tails

  msp2-agent:
    container_name: msp2-agent
    build:
      context: ./aries-cloudagent-python
      dockerfile: ./docker/Dockerfile.run
    ports:
      - 10000:10000
      - 8050:8050
    entrypoint: aca-py
    command: >
      start
        --auto-provision
        --tails-server-base-url http://${ip_address}:6544
        --webhook-url http://${ip_address}:9229
        --auto-respond-credential-proposal
        --auto-respond-credential-offer
        --auto-respond-credential-request
        --auto-verify-presentation
        --inbound-transport http 0.0.0.0 10000
        --inbound-transport ws 0.0.0.0 10001
        --outbound-transport ws
        --outbound-transport http
        --genesis-url http://${ip_address}:9000/genesis
        --log-level info
        --seed 000000000000000000000000Steward2
        --wallet-type indy
        --wallet-key StewardWallet2
        --wallet-name StewardWallet2
        --admin-insecure-mode
        --admin 0.0.0.0 8050
        -e http://${ip_address}:10000
        -l Lufthansa
    # volumes:
      # - ${dir_name}/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis
      # - ${dir_name}/.indy_client_hr:/home/indy/.indy_client

  verifier-server:
    container_name: verifier-server
    build:
      context: .
      dockerfile: ./Dockerfile_server.run
    ports:
      - 6229:6229
    command: >
      node MSP_server.js
        --ip ${ip_address}
        --port 6229
        --name "Ticket Inspector"
        --agentUrl http://${ip_address}:12080
        --schemaName Verifier
        --imageUrl https://cdn0.iconfinder.com/data/icons/railway-station-solid/128/ticket-collector_ticket_collector_ticket-taker_checker_person_-512.png
    depends_on:
      - verifier-agent

  verifier-tails-server:
   container_name: verifier-tails-server
   build:
      context: ./indy-tails-server
      dockerfile: ./docker/Dockerfile.tails-server
   ports:
      - 6546:6546
   command: >
      tails-server
        --host 0.0.0.0
        --port 6546
        --log-level debug
        --storage-path /home/indy/tails
   volumes:
       - ${dir_name}/.indy_tails:/home/indy/tails

  verifier-agent:
    container_name: verifier-agent
    build:
      context: ./aries-cloudagent-python
      dockerfile: ./docker/Dockerfile.run
    ports:
      - 12000:12000
      - 12080:12080
    entrypoint: aca-py
    command: >
      start
        --auto-provision
        --webhook-url http://${ip_address}:6229
        --auto-respond-credential-proposal 
        --auto-respond-credential-offer 
        --auto-respond-credential-request
        --auto-verify-presentation 
        --inbound-transport http 0.0.0.0 12000
        --inbound-transport ws 0.0.0.0 12001
        --outbound-transport ws 
        --outbound-transport http
        --genesis-url http://${ip_address}:9000/genesis
        --log-level info
        --seed 000000000000000000000000Verifier
        --wallet-type indy
        --wallet-local-did
        --wallet-key VerifierWallet
        --wallet-name VerifierWallet
        --admin-insecure-mode 
        --admin 0.0.0.0 12080
        -e http://${ip_address}:12000
        -l Verifier
    # volumes:
      # - ${dir_name}/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis
      # - ${dir_name}/.indy_client_intranet:/home/indy/.indy_client
